name: eqf
version: '1.0-SNAPSHOT'
main: com.lunar_prototype.eqf.EQFPlugin
api-version: '1.21'
authors: [Gemini,RS_Studio(Lunar_prototype)]
description: Echoes Quest Framework - DSL based quest engine.
softdepend : [EDF-Project]

commands:
  eqf:
    description: EQFの管理コマンド
    usage: /eqf <command>
    permission: eqf.admin
    aliases: [quest, eq]

permissions:
  eqf.admin:
    description: EQFの全ての管理権限
    default: op